version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: basket-mongodb
    environment:
      MONGO_INITDB_DATABASE: basket-service
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - basket-network
    command: mongod --replSet rs0
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: basket-redis
    command: redis-server --requirepass sa
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - basket-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data:
  redis_data:

networks:
  basket-network:
    driver: bridge

